# Generated by Django 3.2.9 on 2021-12-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_slackuser_is_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='dialogflowintent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentName', models.CharField(max_length=1000)),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
